### ISSUE TITLE
Putting pyvlasiator on search path

### ISSUE THREAD

**Issue by czhou135** [henry2004y/pyvlasiator#8]
When importing modules from pyvlasiator, the system is unable to find the file without adding the location to the search path:

`from pyvlasiator.vlsv import Vlsv`

Exception has occurred: ModuleNotFoundError
No module named 'pyvlasiator'
  File "C:\Users\czhou\Downloads\Astro\Dong Group\load_data.py", line 5, in <module>
    from pyvlasiator.vlsv import Vlsv
ModuleNotFoundError: No module named 'pyvlasiator'

-----

Adding the following gives access to the files, but there's probably a more efficient way to do so:

```
import sys
sys.path.append('pyvlasiator-main/src')
sys.path.append('pyvlasiator-main/data')
```

**Comment by henry2004y** [comment]
For a not registered package, one way to use it is to add it to an environment variable named `PYTHONPATH`:

```python
export PYTHONPATH=$PYTHONPATH:$HOME/pyvlasiator-main
```

**Comment by henry2004y** [comment]
This is no longer needed as `pyvlasiator` is now registered in PyPI!
